server:
  port: 8889

spring:
  datasource:
    username: root
#    password: 123123123    #EqCvN3FP
    password: EqCvN3FP
    url: jdbc:mysql://127.0.0.1/zph?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    url: jdbc:mysql://47.96.146.104/zph?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

---
#####  由于默认的是UTC时间，所以在中国有8个小时的时差，需要将serverTimezone的值改为GMT%2B8
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zph?serverTimezone=GMT%2B8
#    url: jdbc:mysql://47.96.146.104:3306/zph?serverTimezone=GMT%2B8


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql   //EqCvN3FP
logging:
  level:
    com:
      example:
        mapper : debug

###2020-07-13添加
#日志打印 - logging.file=target/app.log
#参考网址：https://blog.csdn.net/u014248473/article/details/88072072
#logging:
  file: target/app.log

